-- Brand 데모 데이터 생성 (빈티지 아카이브 + 현행 인지도 높은 브랜드 100개)
-- id는 BigInt autoincrement이므로 자동 생성됨
INSERT INTO brand (name, kr_name) 
VALUES 
  -- 브랜드 미상/기타 (3개)
  ('Unknown', '브랜드 미상'),
  ('Other', '기타'),
  ('Vintage', '빈티지'),
  
  -- 클래식 빈티지 아메리칸 브랜드 (20개)
  ('Levi''s', '리바이스'),
  ('Carhartt', '칼하트'),
  ('RRL', '더블알엘'),
  ('Wrangler', '랭글러'),
  ('Lee', '리'),
  ('Champion', '챔피온'),
  ('Russell Athletic', '러셀 애슬레틱'),
  ('Hanes', '헤인즈'),
  ('Patagonia', '파타고니아'),
  ('The North Face', '노스페이스'),
  ('L.L.Bean', '엘엘빈'),
  ('Brooks Brothers', '브룩스 브라더스'),
  ('Pendleton', '펜들턴'),
  ('Filson', '필슨'),
  ('Red Wing', '레드윙'),
  ('Schott', '쇼트'),
  ('Avirex', '아비렉스'),
  ('Alpha Industries', '알파 인더스트리'),
  ('Dickies', '딕키즈'),
  ('Ben Davis', '벤 데이비스'),
  
  -- 빈티지 유럽 브랜드 (15개)
  ('Burberry', '버버리'),
  ('Barbour', '바버'),
  ('Aquascutum', '아쿠아스큐텀'),
  ('Lacoste', '라코스테'),
  ('Fred Perry', '프레드 페리'),
  ('Baracuta', '바라쿠타'),
  ('Belstaff', '벨스타프'),
  ('Clarks', '클락스'),
  ('Dr. Martens', '닥터마틴'),
  ('Adidas Originals', '아디다스 오리지널스'),
  ('Puma', '퓨마'),
  ('Reebok', '리복'),
  ('Ellesse', '엘레쎄'),
  ('Fila', '휠라'),
  ('Kappa', '카파'),
  
  -- 럭셔리 하이엔드 (20개)
  ('Gucci', '구찌'),
  ('Louis Vuitton', '루이비통'),
  ('Prada', '프라다'),
  ('Dior', '디올'),
  ('Chanel', '샤넬'),
  ('Hermès', '에르메스'),
  ('Balenciaga', '발렌시아가'),
  ('Saint Laurent', '생로랑'),
  ('Givenchy', '지방시'),
  ('Bottega Veneta', '보테가 베네타'),
  ('Fendi', '펜디'),
  ('Celine', '셀린느'),
  ('Valentino', '발렌티노'),
  ('Loewe', '로에베'),
  ('Moncler', '몽클레어'),
  ('Tom Ford', '톰포드'),
  ('Salvatore Ferragamo', '살바토레 페라가모'),
  ('Balmain', '발망'),
  ('Versace', '베르사체'),
  ('Armani', '아르마니'),
  
  -- 스트릿웨어 & 컨템포러리 (20개)
  ('Supreme', '슈프림'),
  ('Stüssy', '스투시'),
  ('A Bathing Ape', '어 베이싱 에이프'),
  ('Palace', '팔라스'),
  ('Off-White', '오프화이트'),
  ('Fear of God', '피어 오브 갓'),
  ('Stone Island', '스톤 아일랜드'),
  ('C.P. Company', '씨피 컴퍼니'),
  ('Acne Studios', '아크네 스튜디오'),
  ('Marni', '마르니'),
  ('Maison Margiela', '메종 마르지엘라'),
  ('Rick Owens', '릭 오웬스'),
  ('Jil Sander', '질 샌더'),
  ('Lemaire', '르메르'),
  ('The Row', '더 로우'),
  ('Our Legacy', '아워 레거시'),
  ('AMI Paris', '아미 파리'),
  ('APC', '아페세'),
  ('Ami', '아미'),
  ('Norse Projects', '노르스 프로젝트'),
  
  -- 스포츠 & 스니커즈 (10개)
  ('Nike', '나이키'),
  ('Adidas', '아디다스'),
  ('New Balance', '뉴발란스'),
  ('Asics', '아식스'),
  ('Vans', '반스'),
  ('Converse', '컨버스'),
  ('Salomon', '살로몬'),
  ('Hoka One One', '호카 원원'),
  ('On Running', '온 러닝'),
  ('Saucony', '써코니'),
  
  -- 일본 브랜드 (10개)
  ('Comme des Garçons', '꼼데가르송'),
  ('Yohji Yamamoto', '요지 야마모토'),
  ('Issey Miyake', '이세이 미야케'),
  ('Visvim', '비스빔'),
  ('Kapital', '캐피탈'),
  ('Needles', '니들스'),
  ('Neighborhood', '네이버후드'),
  ('WTAPS', '더블탭스'),
  ('Undercover', '언더커버'),
  ('Sacai', '사카이'),
  
  -- 한국 브랜드 (5개)
  ('Ader Error', '아더에러'),
  ('Gentle Monster', '젠틀몬스터'),
  ('Andersson Bell', '앤더슨벨'),
  ('Wooyoungmi', '우영미'),
  ('Juun.J', '준지');

